import { Link } from 'wouter';
import { PageHeader } from '@/components/PageHeader';

export function TermsAndConditions() {
  return <main className="mx-auto max-w-4xl px-5 py-12 lg:px-8 lg:py-16"><PageHeader eyebrow="ENRG policies" title="Terms & Conditions" description="Terms for using ENRG’s solar marketplace and project services." /><div className="mt-8 space-y-6 rounded-3xl border border-border bg-card p-6 text-sm leading-7 text-muted-foreground sm:p-9"><p>By creating an ENRG account, you agree to provide accurate account and project information, keep your sign-in credentials secure, and use the platform lawfully.</p><section><h2 className="font-display text-xl font-bold text-foreground">Platform services</h2><p className="mt-2">ENRG helps customers discover solar companies, request quotations, and follow project updates. Product and installation agreements are made with the relevant provider or installer, who is responsible for its own scope, pricing, warranties, and delivery.</p></section><section><h2 className="font-display text-xl font-bold text-foreground">Accounts and project updates</h2><p className="mt-2">You are responsible for activity on your account. Customers can view project updates; assigned companies may submit authorized project milestones. Do not attempt to access or modify another person’s account or project.</p></section><section><h2 className="font-display text-xl font-bold text-foreground">Contact</h2><p className="mt-2">For questions about these terms, contact ENRG through the contact details published on the platform.</p></section><Link href="/privacy-policy" className="font-semibold text-accent underline">Read the Privacy Policy</Link></div></main>;
}

export function PrivacyPolicy() {
  return <main className="mx-auto max-w-4xl px-5 py-12 lg:px-8 lg:py-16"><PageHeader eyebrow="ENRG policies" title="Privacy Policy" description="How ENRG uses account and solar project information." /><div className="mt-8 space-y-6 rounded-3xl border border-border bg-card p-6 text-sm leading-7 text-muted-foreground sm:p-9"><p>ENRG collects the details you submit, such as your name, contact information, company details, and project requirements, to operate accounts and connect customers with solar providers.</p><section><h2 className="font-display text-xl font-bold text-foreground">Use and sharing</h2><p className="mt-2">Project details are shared with companies that receive or are assigned to your project so they can respond and deliver service. ENRG also uses service providers to host the platform, protect accounts, and process platform communications.</p></section><section><h2 className="font-display text-xl font-bold text-foreground">Retention and security</h2><p className="mt-2">ENRG retains information for account, project, security, and legal recordkeeping needs, and applies access controls intended to protect it. No online service can guarantee absolute security.</p></section><section><h2 className="font-display text-xl font-bold text-foreground">Your choices</h2><p className="mt-2">You may contact ENRG to ask about your account information or request correction where available. Transactional project and maintenance messages may be sent when needed to provide requested services.</p></section><Link href="/terms-and-conditions" className="font-semibold text-accent underline">Read the Terms &amp; Conditions</Link></div></main>;
}
